"""SQLAlchemy/SQLModel declarative base setup.

We assign a deterministic naming convention to ``SQLModel.metadata`` in Phase 0
so that later phases' models get explicit, stable constraint/index names both
in the ORM and in Alembic autogenerated diffs.
"""

from sqlalchemy import MetaData
from sqlmodel import SQLModel

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_N_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

SQLModel.metadata = MetaData(naming_convention=NAMING_CONVENTION)
